name: CI/CD Site HTML

on:
  push:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Validar HTML
        uses:  Cyb3r-Jak3/html5validator-action@v0.4.4

  deploy:
    runs-on: ubuntu-latest
    needs: validate # só roda se a valida~ção passar
    steps:
      - uses: actions/checkout@v3
      - name: Deploy no Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_tokeb: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
